version: '3.1'

networks:
  front:
  back:


services:

  db:
    image: mongo
    container_name: db
    restart: on-failure:10
    networks:
      - back
    ports:
      - 27017:27017
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: 'trasteroadmin'
#      MONGO_INITDB_ROOT_PASSWORD: 'trasteroadmin123!'
#    volumes:
#      - 'mongo:/data/db'

  mongo-express:
    depends_on:
      - db
    image: mongo-express
    restart: on-failure:10
    networks:
      - back
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: 'db'
#      ME_CONFIG_MONGODB_ADMINUSERNAME: 'trasteroadmin'
#      ME_CONFIG_MONGODB_ADMINPASSWORD: 'trasteroadmin123!'
#      ME_CONFIG_BASICAUTH_USERNAME: 'trastero'
#      ME_CONFIG_BASICAUTH_PASSWORD: 'trastero123!'

  api:
    depends_on:
      - db
    image: trastero-server
    container_name: api
    restart: on-failure:10
    networks:
      - back
    ports:
      - 5000:5000
    environment:
      TRASTERO_MONGO_DB_NAME: 'trastero'
      TRASTERO_MONGO_HOST: 'mongodb://db'
      TRASTERO_MONGO_PORT: 27017
#      TRASTERO_MONGO_USERNAME: 'trastero'
#      TRASTERO_MONGO_PASSWORD: 'trastero123!'
    volumes:
      - ..:${APP_WORKDIR}

  nginx:
    depends_on:
      - api
    # FIXME: turn this into custom container
    image: nginx
    volumes:
     - ../conf.d/nginx.conf.template:/etc/nginx/conf.d/default.conf:ro
#     - ../conf.d/nginx.conf.template:/etc/nginx/conf.d/trastero.nginx.conf.template:ro
     - ../trastero-ui/build:/usr/share/nginx/html:ro
    ports:
     - 8080:80
    networks:
      - front
      - back
    command: [nginx-debug, '-g', 'daemon off;']
#    environment:
#     NGINX_HOST: localhost
#     NGINX_PORT: 80
#     TRASTERO_API_HOST: api
#     TRASTERO_API_PORT: 5000
#     TRASTERO_HTML_DIR: /usr/share/nginx/html
#    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/trastero.nginx.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
